on:
  push:
    branches: ["*"]
    tags-ignore: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install tools
      run: |
        Gsh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d v3.0.0
        sudo mv ./bin/task /usr/local/bin

    - name: Build
      run: task build
